<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HumbleEngine.HAL\HumbleEngine.HAL.csproj" />
    <ProjectReference Include="..\HumbleEngine.HAL.Linux\HumbleEngine.HAL.Linux.csproj" />
    <ProjectReference Include="..\HumbleEngine.SceneGraph\HumbleEngine.SceneGraph.csproj" />
    <ProjectReference Include="..\HumbleEngine.Text\HumbleEngine.Text.csproj" />
    <ProjectReference Include="..\HumbleEngine.Editor\HumbleEngine.Editor.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
