<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HumbleEngine.Vulkan</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HumbleEngine.Core\HumbleEngine.Core.csproj" />
        <ProjectReference Include="..\HumbleEngine.X11\HumbleEngine.X11.csproj" />
        <ProjectReference Include="..\HumbleEngine.Wayland\HumbleEngine.Wayland.csproj" />
    </ItemGroup>

</Project>
