<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>HumbleEngine.Linux</RootNamespace>
        <NoWarn>$(NoWarn);CA2255</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HumbleEngine.HAL\HumbleEngine.HAL.csproj" />
        <ProjectReference Include="..\HumbleEngine.HAL.X11\HumbleEngine.HAL.X11.csproj" />
        <ProjectReference Include="..\HumbleEngine.HAL.Wayland\HumbleEngine.HAL.Wayland.csproj" />
        <ProjectReference Include="..\HumbleEngine.HAL.Vulkan\HumbleEngine.HAL.Vulkan.csproj" />
        <ProjectReference Include="..\HumbleEngine.HAL.OpenGL\HumbleEngine.HAL.OpenGL.csproj" />
    </ItemGroup>

</Project>
