<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\HumbleEngine\HumbleEngine.csproj" />
        <ProjectReference Include="..\HumbleEngine.Silk\HumbleEngine.Silk.csproj" />
        <ProjectReference Include="..\HumbleEngine.Skia\HumbleEngine.Skia.csproj" />
    </ItemGroup>

</Project>
